name: Convert Images to WebP
on:
  push:
    branches:
      - main
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cwebp
        run: sudo apt-get install -y webp
      - name: Convert images to WebP
        run: find ./images -name '*.jpg' -or -name '*.png' | xargs -I {} cwebp {} -o {}.webp
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Convert images to WebP'
          git push